- README.md
> #4 feat: 깃컨벤션 readme

- src/index.js
- src/models/database/placeImgs.js
- src/models/database/placeRoutes.js
- src/models/database/places.js
- src/models/database/reviews.js
- src/models/database/routeBookmarks.js
- src/models/database/routeImgs.js
- src/models/database/routeLikes.js
- src/models/database/routes.js
- src/models/database/socialLogins.js
- src/models/database/userImgs.js
- src/models/database/users.js
- src/models/index.js
> feat: #6 model오류 수정

- Dockerfile
- package.json
- src/repositories/README.md
> feat:#6 dockerfile

- package-lock.json
- package.json
- src/repositories/socialLogin/socialLogin.repository.js
- src/services/socialLogin/socialLogin.service.js
> #14 
> 수정 내용
이름, 성별, 생년월일, 만든시각, 업데이트시각, 계정상태 업로드 가능하도록 수정했습니다.
> birth의 데이터타입이 datetime이라 시간:분:초 까지 들어가는데 이부분은 굳이 필요하지 않을 것 같아서 date타입으로 변경하면 어떨까요?
> fix:#18 카카오 사용자정보

- config/tmap.config.js
- src/controllers/maps/place.controller.js
- src/dtos/maps/place.dto.js
- src/index.js
- src/repositories/maps/place.repository.js
- src/routes/maps/place.routes.js
- src/services/maps/place.service.js
#24 
Tmap POI API 연동을 통한 장소 실시간 검색 기능을 구현하였습니다.
검색 키워드를 기반으로 장소 목록을 가져오고, 프론트 요구 형식(lat, lng, place_name 등)에 맞춰 응답합니다.
**1. Tmap API 연동**
- .env에 TMAP_API_KEY 등록
- config/tmap.config.js를 통해 dotenv 로딩 및 키 관리
**2. 서비스 계층 구현 (searchPlacesFromTmap)**
- axios로 Tmap /tmap/pois API 호출
- 응답 결과를 DTO로 변환 (PlaceResponseDto)
- location: "위도,경도" 문자열 생성 후 응답에 lat, lng로 분리
**3. DTO 구성**
- PlaceResponseDto: place_name, place_id, lat, lng, address 반환
- 내부적으로 location 문자열에서 위/경도 추출
**4. 라우터 및 컨트롤러 구성**
- GET /api/places?query=키워드 엔드포인트 구현
- 검색어 누락 시 400 반환, 정상 호출 시 200 + 가공된 장소 리스트 반환
> ✨ feat: 장소 검색 개발

- src/models/index.js
모델 index.js에서 모델 파일 불러올 때 placeImg.js랑 placeRoutes.js가 누락되어있는 오류가 있어서 추가하였습니다 
>
> 🐛 fix : 모델 파일 누락 수정

- src/services/marking/osm.service.js
- src/sockets/locationSocket.js
- src/sockets/socket.controller.js
> ex) #39
벤치, 가로등 마킹 데이터를 가져와 반환합니다.
벤치 정보는 실시간 위치 기준으로 제공됩니다.
내실시간 위치에 따른 벤치 마킹 데이터 가져오기
> feat: bench 실시간 위치 가져오기->장소명, 주소명 추가 필요

- src/sockets/socket.controller.js
- src/sockets/socket.routes.js
> feat:#48 가까운 벤치 반환

- src/controllers/road/road.share.controller.js
- src/dtos/road/road.share.dto.js
- src/repositories/road/road.search.repository.js
- src/repositories/road/road.share.repository.js
- src/routes/road/road.routes.js
- src/services/road/road.share.service.js
> #52 
> 루트 sns 공유 링크 생성 개발하였습니다 
- 이 링크는 사용자가 클릭했을 때 "공유된 루트 상세 페이지"로 연결
- 프론트엔드에서 공유용 페이지(/share/routes/:id)를 만들고, 이 링크로 라우팅되도록 추후에 개발 진행 
>
> ✨feat: 루트 sns 공유 링크 생성 개발

- src/controllers/road/road.controller.js
- src/repositories/auth/auth.signup.repository.js
- src/repositories/road/road.review.repository.js
- src/routes/road/road.routes.js
- src/services/road/road.service.js
> ex) #45 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> Refactor: 루트 리뷰 수정 API 리펙토링

- src/controllers/bookmark/bookmark.controller.js
- src/index.js
- src/repositories/bookmark/bookmark.repository.js
- src/routes/bookmark/bookmark.routes.js
> #77 
> 루트 북마크 토글 형식으로 생성/취소 기능
>
> feat: 루트 북마크 토글

- src/controllers/bookmark/bookmark.controller.js
- src/repositories/bookmark/bookmark.repository.js
- src/routes/bookmark/bookmark.routes.js
> #79 
> 사용자별로 루트 북마크한 내역 조회 커서 페이징
> 사용자 인증 토큰으로 구분, user_id별로 북마크한 것들만 조회되도록 구현함
다른 자용자의 토큰으로 테스트한 결과 
>
> feat: 루트 북마크 조회

- src/services/maps/place.service.js
> #90 
> 장소 검색 리팩토링 
- Tmap 장소 검색 API에서 중복 장소가 응답되는 문제 해결  
→ `poi.id` 기준으로 중복 제거 (`Map` 활용)
>
> ♻️refactor: 장소 검색 리팩토링

- config/tmap.config.js
> 🐛 hotfix :  api 키 누락

- src/controllers/maps/place.rating.controller.js
- src/controllers/maps/place.review.controller.js
- src/dtos/maps/place.dto.js
- src/repositories/maps/place.review.repository.js
- src/services/maps/place.review.service.js
> #103 
>
- 장소 리뷰 등록 시 유저 정보(nickname, 프로필 이미지) 포함되도록 응답 구조 개선
- createOrUpdateReview 서비스 내에서 리뷰 등록 후 유저 정보까지 포함된 리뷰 fetch 처리 추가
- PlaceReviewResponseDto에서 User.nickname, User.UserImg.imageUrl까지 포함해 반환되도록 구조 확장
- findReviewWithUserByUserAndPlace 함수 구현 및 적용 (User, UserImg 포함 eager loading)
>
> refactor : 장소 리뷰 생성, 페이징 리팩토링 

- src/controllers/bookmark/place.bookmark.controller.js
- src/routes/bookmark/bookmark.routes.js
- src/utils/tmap.js
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> Fix: 화딱지 잔뜩나는 장소 북마크 수정 완료 씨익씨익

- src/dtos/maps/place.dto.js
- src/services/maps/place.review.service.js
> hotfix: 장소 별점 반환값 수정

- src/controllers/maps/place.review.controller.js
- src/routes/maps/place.routes.js
> ✨ feature : 별점 로직 티맵아이디 추가

- src/controllers/maps/place.review.controller.js
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> ✨ feature : 티맵 아이디 저장 로직

- src/controllers/auth/auth.controller.js
- src/repositories/socialLogin/socialLogin.repository.js
- src/routes/auth/auth.routes.js
> ex) #이슈번호, #이슈번호
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>
> Feat: userId기반 조회
